version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: 
      context: .
      dockerfile: ./docker/go/Dockerfile # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定    
    ports: 
      - "3000:3000"
      - "3001:3001"
    command: gin run main.go


      
